
export const ConstentData = [
    {
        id: 1,
        product: 'vegetables',
        name: "fruits & vegetables",
        img: '/images/potato.webp',
        title: 'Potato',
        qty: '500 gm',
        price: '20',
    },
    {
        id: 2,
        product: 'fruits',
        name: "fruits & vegetables",
        img: '/images/avocado.webp',
        title: 'Avocado',
        price: '60',
        qty: '1',
    },
    {
        id: 3,
        product: 'vegetables',
        name: "fruits & vegetables",
        img: '/images/broccoli.webp',
        title: 'Broccoli',
        price: '30',
        qty: '500 gm',
    },
    {
        id: 4,
        product: "ghee",
        name:"tea ,coffee & more",
        img: '/images/desi-ghee.webp',
        title: 'Desi Ghee',
        qty: '500 gm',
        price: '450',
    },
    {
        id: 5,
        product: 'fruits',
        name: "fruits & vegetables",
        img: '/images/kiwi-green.webp',
        title: 'Kiwi',
        price: '40',
        qty: '1',
    },
    {
        id: 6,
        product: 'vegetables',
        name: "fruits & vegetables",
        img: '/images/sweet-corn.webp',
        title: 'Sweet Corn',
        price: '30',
        qty: '250 gm',
    },
    {
        id: 7,
        product: 'fruits',
        name: "fruits & vegetables",
        img: '/images/guava-thai.webp',
        title: 'Guava',
        price: '25',
        qty: '500 gm',
    },
    {
        id: 8,
        product: "ghee",
        name:"tea ,coffee & more",
        img: '/images/desi-ghee-granular.webp',
        title: 'Desi Ghee Granular',
        price: '300',
        qty: '250 gm',
    },
    {
        id: 9,
        product: 'vegetables',
        name: "fruits & vegetables",
        img: '/images/mushrooms.webp',
        title: 'Mushrooms',
        price: '40',
        qty: '250 gm',
    },
    {
        id: 10,
        product: "chocolate",
        name:"sweet cravings",
        img: '/images/kitkat-chocolate.webp',
        title: 'Kitkat',
        price: '45',
        qty: '45 gm',
    },
    {
        id: 11,
        product: 'vegetables',
        name: "fruits & vegetables",
        img: '/images/capsicum.webp',
        title: 'Capsicum',
        price: '30',
        qty: '500 gm',
    },
    {
        id: 12,
        product: 'fruits',
        name: "fruits & vegetables",
        img: '/images/strawberry.webp',
        title: 'Strawberry',
        price: '45',
        qty: '500 gm',
    },
    {
        id: 13,
        product: "tea",
        name:"tea ,coffee & more",
        img: '/images/tata-gold-leaf.jpeg',
        title: ' Tata Gold Leaf Tea',
        price: '30',
        qty: '100 gm',
    },
    // 
    {
        id: 14,
        product: "fruits",
        name: "fruits & vegetables",
        img: '/images/apple-red.webp',
        title: 'Red Apple',
        price: '30',
        qty: '100 gm',
    },
    {
        id: 15,
        product: "vegetables",
        name: "fruits & vegetables",
        img: '/images/brinjal-green.webp',
        title: 'Green Brinjal Round',
        price: '30',
        qty: '100 gm',
    },
    {
        id: 16,
        product: "fruits",
        name: "fruits & vegetables",
        img: '/images/apple.webp',
        title: 'Apple',
        price: '70',
        qty: '500 gm',
    },
    {
        id: 17,
        product: "ghee",
        name:"tea ,coffee & more",
        img: '/images/cow-ghee.webp',
        title: 'Cow Ghee',
        price: '150',
        qty: '100 gm',
    },
    {
        id: 18,
        product: "vegetables",
        name: "fruits & vegetables",
        img: '/images/green-chilli.webp',
        title: 'Chilli Green',
        price: '15',
        qty: '100 gm',
    },
    {
        id: 19,
        product: "fruits",
        name: "fruits & vegetables",
        img: '/images/fresho-pear-.webp',
        title: 'pear',
        price: '30',
        qty: '100 gm',
    },
    {
        id: 20,
        product: "chocolate",
        name:"sweet cravings",
        img: '/images/silk-chocolate.webp',
        title: 'Silk Chocolate',
        price: '300',
        qty: '250 gm',
    },
    {
        id: 21,
        product: "tea",
        name:"tea ,coffee & more",
        img: '/images/tata-premium.webp',
        title: 'Tata Premium Tea',
        price: '300',
        qty: '250 gm',
    }, {
        id: 22,
        product: "ghee",
        name:"tea ,coffee & more",
        img: '/images/organic-cow-ghee.webp',
        title: 'Cow Ghee Organic',
        price: '300',
        qty: '250 gm',
    }
    , {
        id: 23,
        product: "chocolate",
        name:"sweet cravings",
        img: '/images/nestle-chocolate.jpeg',
        title: 'Nestle Chocolate',
        price: '300',
        qty: '250 gm',
    },
    {
        id: 24,
        product: "tea",
        name:"tea ,coffee & more",
        img: '/images/today-tea.jpeg',
        title: 'Today Tea Limited',
        price: '300',
        qty: '250 gm',
    }, {
        id: 25,
        product: "chocolate",
        name:"sweet cravings",
        img: '/images/dairy-milk.webp',
        title: 'Dairy Milk Nuts & Fruits Chocolate',
        price: '300',
        qty: '250 gm',
    },
    {
        id: 26,
        product: "tea",
        name:"tea ,coffee & more",
        img: '/images/red-label.webp',
        title: 'Red Label Tea',
        price: '300',
        qty: '250 gm',
    }, {
        id: 27,
        product: "vegetables",
        name: "fruits & vegetables",
        img: '/images/lady-finger.webp',
        title: 'Lady Finger',
        price: '20',
        qty: '250 gm',
    },
    {
        id: 28,
        product: "fruits",
        name: "fruits & vegetables",
        img: '/images/banana.webp',
        title: 'Banana',
        price: '30',
        qty: '6 pics',
    },
   {
        id: 29,
        product: "chocolate",
        name:"sweet cravings",
        img: '/images/amul-dark-choco.webp',
        title: 'Amul Dark Chocolate Bar',
        price: '200',
        qty: '150 gm',
    },
     {
        id: 30,
        product: "chocolate",
        name:"sweet cravings",
        img: '/images/amul-fruit&nuts.webp',
        title: 'Dairy Milk Nuts & Fruits Chocolate',
        price: '200',
        qty: '150 gm',
    },
     {
        id: 31,
        product: "chocolate",
        name:"sweet cravings",
        img: '/images/Chokola Sweet.webp',
        title: 'Chokola Sweet Love',
        price: '689',
        qty: '100 g',
    },
     {
        id: 32,
        product: "chocolate",
        name:"sweet cravings",
        img: '/images/Fabelle-The-Bars-Trilogy.webp',
        title: 'Fabelle The Bars Trilogy',
        price: '950',
        qty: '388 g',
    },

]