
export const ConstentData = [
    {
        id: 1,
        product: 'vegetables',
        name: 'fruits & vegetables',
        img: '/images/potato.webp',
        title: 'Potato',
        baseQty: 500,
        baseLabel: 'gm',
        price: 20,
        qty: 1
    },
    {
        id: 2,
        product: 'fruits',
        name: 'fruits & vegetables',
        img: '/images/avocado.webp',
        title: 'Avocado',
        baseQty: 1,
        baseLabel: 'pc',
        price: 60,
        qty: 1
    },
    {
        id: 3,
        product: 'vegetables',
        name: 'fruits & vegetables',
        img: '/images/broccoli.webp',
        title: 'Broccoli',
        baseQty: 500,
        baseLabel: 'gm',
        price: 30,
        qty: 1
    },
    {
        id: 4,
        product: 'ghee',
       name: "tea ,coffee & more",
        img: '/images/desi-ghee.webp',
        title: 'Desi Ghee',
        baseQty: 500,
        baseLabel: 'gm',
        price: 450,
        qty: 1
    },
    {
        id: 5,
        product: 'fruits',
        name: 'fruits & vegetables',
        img: '/images/kiwi-green.webp',
        title: 'Kiwi',
        baseQty: 1,
        baseLabel: 'pc',
        price: 40,
        qty: 1
    },
    {
        id: 6,
        product: 'vegetables',
        name: 'fruits & vegetables',
        img: '/images/sweet-corn.webp',
        title: 'Sweet Corn',
        baseQty: 250,
        baseLabel: 'gm',
        price: 30,
        qty: 1
    },
    {
        id: 7,
        product: 'fruits',
        name: 'fruits & vegetables',
        img: '/images/guava-thai.webp',
        title: 'Guava',
        baseQty: 500,
        baseLabel: 'gm',
        price: 25,
        qty: 1
    },
    {
        id: 8,
        product: 'ghee',
        name: "tea ,coffee & more",
        img: '/images/desi-ghee-granular.webp',
        title: 'Desi Ghee Granular',
        baseQty: 250,
        baseLabel: 'gm',
        price: 300,
        qty: 1
    },
    {
        id: 9,
        product: 'vegetables',
        name: 'fruits & vegetables',
        img: '/images/mushrooms.webp',
        title: 'Mushrooms',
        baseQty: 250,
        baseLabel: 'gm',
        price: 40,
        qty: 1
    },
    {
        id: 10,
        product: 'chocolate',
        name: 'sweet cravings',
        img: '/images/kitkat-chocolate.webp',
        title: 'Kitkat',
        baseQty: 45,
        baseLabel: 'gm',
        price: 45,
        qty: 1
    },
    {
        id: 11,
        product: 'vegetables',
        name: 'fruits & vegetables',
        img: '/images/capsicum.webp',
        title: 'Capsicum',
        baseQty: 500,
        baseLabel: 'gm',
        price: 30,
        qty: 1
    },
    {
        id: 12,
        product: 'fruits',
        name: 'fruits & vegetables',
        img: '/images/strawberry.webp',
        title: 'Strawberry',
        baseQty: 500,
        baseLabel: 'gm',
        price: 45,
        qty: 1
    },
    {
        id: 13,
        product: 'tea',
        name: "tea ,coffee & more",
        img: '/images/tata-gold-leaf.jpeg',
        title: 'Tata Gold Leaf Tea',
        baseQty: 100,
        baseLabel: 'gm',
        price: 30,
        qty: 1,
    },
    // 
    {
        id: 14,
        product: 'fruits',
        name: 'fruits & vegetables',
        img: '/images/apple-red.webp',
        title: 'Red Apple',
        baseQty: 100,
        baseLabel: 'gm',
        price: 30,
        qty: 1,
    },
    {
        id: 15,
        product: 'vegetables',
        name: 'fruits & vegetables',
        img: '/images/brinjal-green.webp',
        title: 'Green Brinjal Round',
        baseQty: 500,
        baseLabel: 'gm',
        price: 30,
        qty: 1
    },
    {
        id: 16,
        product: "fruits",
        name: "fruits & vegetables",
        img: '/images/apple.webp',
        title: 'Apple',
        baseQty: 500,
        baseLabel: 'gm',
        price: '70',
        qty: 1,
    },
    {
        id: 17,
        product: "ghee",
        name: "tea ,coffee & more",
        img: '/images/cow-ghee.webp',
        title: 'Cow Ghee',
        baseQty: 100,
        baseLabel: 'gm',
        price: '150',
        qty: 1,
    },
    {
        id: 18,
        product: "vegetables",
        name: "fruits & vegetables",
        img: '/images/green-chilli.webp',
        title: 'Chilli Green',
        baseQty: 100,
        baseLabel: 'gm',
        price: '15',
        qty: 1,
    },
    {
        id: 19,
        product: "fruits",
        name: "fruits & vegetables",
        img: '/images/fresho-pear-.webp',
        title: 'pear',
        baseQty: 100,
        baseLabel: 'gm',
        price: '30',
        qty: 1,
    },
    {
        id: 20,
        product: "chocolate",
        name: "sweet cravings",
        img: '/images/silk-chocolate.webp',
        title: 'Silk Chocolate',
        baseQty: 250,
        baseLabel: 'gm',
        price: '300',
        qty: 1,
    },
    {
        id: 21,
        product: "tea",
        name: "tea ,coffee & more",
        img: '/images/tata-premium.webp',
        title: 'Tata Premium Tea',
        baseQty: 250,
        baseLabel: 'gm',
        price: '300',
        qty: 1,
    }, {
        id: 22,
        product: "ghee",
        name: "tea ,coffee & more",
        img: '/images/organic-cow-ghee.webp',
        title: 'Cow Ghee Organic',
        baseQty: 250,
        baseLabel: 'gm',
        price: '300',
        qty: 1,
    }
    , {
        id: 23,
        product: "chocolate",
        name: "sweet cravings",
        img: '/images/nestle-chocolate.jpeg',
        title: 'Nestle Chocolate',
        baseQty: 250,
        baseLabel: 'gm',
        price: '300',
        qty: 1,
    },
    {
        id: 24,
        product: "tea",
        name: "tea ,coffee & more",
        img: '/images/today-tea.jpeg',
        title: 'Today Tea Limited',
        baseQty: 250,
        baseLabel: 'gm',
        price: '300',
        qty: 1,
    }, {
        id: 25,
        product: "chocolate",
        name: "sweet cravings",
        img: '/images/dairy-milk.webp',
        title: 'Dairy Milk Nuts & Fruits Chocolate',
        baseQty: 250,
        baseLabel: 'gm',
        price: '300',
        qty: 1,
    },
    {
        id: 26,
        product: "tea",
        name: "tea ,coffee & more",
        img: '/images/red-label.webp',
        title: 'Red Label Tea',
        baseQty: 250,
        baseLabel: 'gm',
        price: '300',
        qty: 1,
    }, {
        id: 27,
        product: "vegetables",
        name: "fruits & vegetables",
        img: '/images/lady-finger.webp',
        title: 'Lady Finger',
        baseQty: 250,
        baseLabel: 'gm',
        price: '20',
        qty: 1,
    },
    {
        id: 28,
        product: "fruits",
        name: "fruits & vegetables",
        img: '/images/banana.webp',
        title: 'Banana',
        baseQty: 6,
        baseLabel: 'pc',
        price: '30',
        qty: 1,
    },
    {
        id: 29,
        product: "chocolate",
        name: "sweet cravings",
        img: '/images/amul-dark-choco.webp',
        title: 'Amul Dark Chocolate Bar',
        baseQty: 150,
        baseLabel: 'gm',
        price: '200',
        qty: 1,
    },
    {
        id: 30,
        product: "chocolate",
        name: "sweet cravings",
        img: '/images/amul-fruit&nuts.webp',
        title: 'Amul Nuts & Fruits Chocolate',
        baseQty: 150,
        baseLabel: 'gm',
        price: '200',
        qty: 1,
    },
    {
        id: 31,
        product: "chocolate",
        name: "sweet cravings",
        img: '/images/Chokola Sweet.webp',
        title: 'Chokola Sweet Love',
        baseQty: 100,
        baseLabel: 'gm',
        price: '689',
        qty: 1,
    },
    {
        id: 32,
        product: "chocolate",
        name: "sweet cravings",
        img: '/images/Fabelle-The-Bars-Trilogy.webp',
        title: 'Fabelle The Bars Trilogy',
        baseQty: 388,
        baseLabel: 'gm',
        price: '950',
        qty: 1,
    }

]